name: pruebas_ciTaller

on:
  push:
    branches: [ main ]

jobs:

  verificar_codigo:

    runs-on: ubuntu-latest

    steps:
      - name: checkout del repositorio
        uses: actions/checkout@v4

      - name: mostrar archivos(opcional)
        run: ls -R


  desplegar_pagina:

    needs: verificar_codigo

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir Artifactos de Despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Iniciar Despliegue a Pages
        id: deployment
        uses: actions/deploy-pages@v4